# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: moderation.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'moderation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10moderation.proto\x12\nmoderation\"F\n\x0fModerateRequest\x12\x12\n\ncomment_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x11\n\tauthor_id\x18\x03 \x01(\t\"c\n\x07Verdict\x12\x12\n\ncomment_id\x18\x01 \x01(\t\x12&\n\x08\x64\x65\x63ision\x18\x02 \x01(\x0e\x32\x14.moderation.Decision\x12\r\n\x05score\x18\x03 \x01(\x02\x12\r\n\x05stage\x18\x04 \x01(\t*I\n\x08\x44\x65\x63ision\x12\x18\n\x14\x44\x45\x43ISION_UNSPECIFIED\x10\x00\x12\x0b\n\x07\x41PPROVE\x10\x01\x12\n\n\x06REJECT\x10\x02\x12\n\n\x06REVIEW\x10\x03\x32J\n\nModeration\x12<\n\x08Moderate\x12\x1b.moderation.ModerateRequest\x1a\x13.moderation.VerdictB*Z(github.com/you/moderation-demo/api/pb;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'moderation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(github.com/you/moderation-demo/api/pb;pb'
  _globals['_DECISION']._serialized_start=205
  _globals['_DECISION']._serialized_end=278
  _globals['_MODERATEREQUEST']._serialized_start=32
  _globals['_MODERATEREQUEST']._serialized_end=102
  _globals['_VERDICT']._serialized_start=104
  _globals['_VERDICT']._serialized_end=203
  _globals['_MODERATION']._serialized_start=280
  _globals['_MODERATION']._serialized_end=354
# @@protoc_insertion_point(module_scope)
