// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: moderation.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Moderation_Moderate_FullMethodName = "/moderation.Moderation/Moderate"
)

// ModerationClient is the client API for Moderation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModerationClient interface {
	Moderate(ctx context.Context, in *ModerateRequest, opts ...grpc.CallOption) (*Verdict, error)
}

type moderationClient struct {
	cc grpc.ClientConnInterface
}

func NewModerationClient(cc grpc.ClientConnInterface) ModerationClient {
	return &moderationClient{cc}
}

func (c *moderationClient) Moderate(ctx context.Context, in *ModerateRequest, opts ...grpc.CallOption) (*Verdict, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Verdict)
	err := c.cc.Invoke(ctx, Moderation_Moderate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModerationServer is the server API for Moderation service.
// All implementations must embed UnimplementedModerationServer
// for forward compatibility.
type ModerationServer interface {
	Moderate(context.Context, *ModerateRequest) (*Verdict, error)
	mustEmbedUnimplementedModerationServer()
}

// UnimplementedModerationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModerationServer struct{}

func (UnimplementedModerationServer) Moderate(context.Context, *ModerateRequest) (*Verdict, error) {
	return nil, status.Error(codes.Unimplemented, "method Moderate not implemented")
}
func (UnimplementedModerationServer) mustEmbedUnimplementedModerationServer() {}
func (UnimplementedModerationServer) testEmbeddedByValue()                    {}

// UnsafeModerationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModerationServer will
// result in compilation errors.
type UnsafeModerationServer interface {
	mustEmbedUnimplementedModerationServer()
}

func RegisterModerationServer(s grpc.ServiceRegistrar, srv ModerationServer) {
	// If the following call panics, it indicates UnimplementedModerationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Moderation_ServiceDesc, srv)
}

func _Moderation_Moderate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServer).Moderate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Moderation_Moderate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServer).Moderate(ctx, req.(*ModerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Moderation_ServiceDesc is the grpc.ServiceDesc for Moderation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Moderation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "moderation.Moderation",
	HandlerType: (*ModerationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Moderate",
			Handler:    _Moderation_Moderate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "moderation.proto",
}
