// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: moderation.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Decision int32

const (
	Decision_DECISION_UNSPECIFIED Decision = 0
	Decision_APPROVE              Decision = 1
	Decision_REJECT               Decision = 2
	Decision_REVIEW               Decision = 3
)

// Enum value maps for Decision.
var (
	Decision_name = map[int32]string{
		0: "DECISION_UNSPECIFIED",
		1: "APPROVE",
		2: "REJECT",
		3: "REVIEW",
	}
	Decision_value = map[string]int32{
		"DECISION_UNSPECIFIED": 0,
		"APPROVE":              1,
		"REJECT":               2,
		"REVIEW":               3,
	}
)

func (x Decision) Enum() *Decision {
	p := new(Decision)
	*p = x
	return p
}

func (x Decision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Decision) Descriptor() protoreflect.EnumDescriptor {
	return file_moderation_proto_enumTypes[0].Descriptor()
}

func (Decision) Type() protoreflect.EnumType {
	return &file_moderation_proto_enumTypes[0]
}

func (x Decision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Decision.Descriptor instead.
func (Decision) EnumDescriptor() ([]byte, []int) {
	return file_moderation_proto_rawDescGZIP(), []int{0}
}

type ModerateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     string                 `protobuf:"bytes,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	AuthorId      string                 `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModerateRequest) Reset() {
	*x = ModerateRequest{}
	mi := &file_moderation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModerateRequest) ProtoMessage() {}

func (x *ModerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModerateRequest.ProtoReflect.Descriptor instead.
func (*ModerateRequest) Descriptor() ([]byte, []int) {
	return file_moderation_proto_rawDescGZIP(), []int{0}
}

func (x *ModerateRequest) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *ModerateRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ModerateRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

type Verdict struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     string                 `protobuf:"bytes,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	Decision      Decision               `protobuf:"varint,2,opt,name=decision,proto3,enum=moderation.Decision" json:"decision,omitempty"`
	Score         float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	Stage         string                 `protobuf:"bytes,4,opt,name=stage,proto3" json:"stage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Verdict) Reset() {
	*x = Verdict{}
	mi := &file_moderation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Verdict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verdict) ProtoMessage() {}

func (x *Verdict) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verdict.ProtoReflect.Descriptor instead.
func (*Verdict) Descriptor() ([]byte, []int) {
	return file_moderation_proto_rawDescGZIP(), []int{1}
}

func (x *Verdict) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *Verdict) GetDecision() Decision {
	if x != nil {
		return x.Decision
	}
	return Decision_DECISION_UNSPECIFIED
}

func (x *Verdict) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Verdict) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

var File_moderation_proto protoreflect.FileDescriptor

const file_moderation_proto_rawDesc = "" +
	"\n" +
	"\x10moderation.proto\x12\n" +
	"moderation\"a\n" +
	"\x0fModerateRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\tR\tcommentId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\tR\bauthorId\"\x86\x01\n" +
	"\aVerdict\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\tR\tcommentId\x120\n" +
	"\bdecision\x18\x02 \x01(\x0e2\x14.moderation.DecisionR\bdecision\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\x12\x14\n" +
	"\x05stage\x18\x04 \x01(\tR\x05stage*I\n" +
	"\bDecision\x12\x18\n" +
	"\x14DECISION_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aAPPROVE\x10\x01\x12\n" +
	"\n" +
	"\x06REJECT\x10\x02\x12\n" +
	"\n" +
	"\x06REVIEW\x10\x032J\n" +
	"\n" +
	"Moderation\x12<\n" +
	"\bModerate\x12\x1b.moderation.ModerateRequest\x1a\x13.moderation.VerdictB*Z(github.com/you/moderation-demo/api/pb;pbb\x06proto3"

var (
	file_moderation_proto_rawDescOnce sync.Once
	file_moderation_proto_rawDescData []byte
)

func file_moderation_proto_rawDescGZIP() []byte {
	file_moderation_proto_rawDescOnce.Do(func() {
		file_moderation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_moderation_proto_rawDesc), len(file_moderation_proto_rawDesc)))
	})
	return file_moderation_proto_rawDescData
}

var file_moderation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_moderation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_moderation_proto_goTypes = []any{
	(Decision)(0),           // 0: moderation.Decision
	(*ModerateRequest)(nil), // 1: moderation.ModerateRequest
	(*Verdict)(nil),         // 2: moderation.Verdict
}
var file_moderation_proto_depIdxs = []int32{
	0, // 0: moderation.Verdict.decision:type_name -> moderation.Decision
	1, // 1: moderation.Moderation.Moderate:input_type -> moderation.ModerateRequest
	2, // 2: moderation.Moderation.Moderate:output_type -> moderation.Verdict
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_moderation_proto_init() }
func file_moderation_proto_init() {
	if File_moderation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_moderation_proto_rawDesc), len(file_moderation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_moderation_proto_goTypes,
		DependencyIndexes: file_moderation_proto_depIdxs,
		EnumInfos:         file_moderation_proto_enumTypes,
		MessageInfos:      file_moderation_proto_msgTypes,
	}.Build()
	File_moderation_proto = out.File
	file_moderation_proto_goTypes = nil
	file_moderation_proto_depIdxs = nil
}
